### ISSUE TITLE
Direct Lock Code or LCM

### ISSUE THREAD

**Issue by ChrisOgden** [klinquist/airbnbScheduler#2]
It looks like this is setting lock codes directly on the device versus through the Hubitat Lock Code manager, is that correct? I am looking to enhance this to use OwnerRez API as the source instead.

**Comment by klinquist** [comment]
Lock code manager just stores name associations.  LCM will show codes stored in the lock (by this integration), even if there is no associated name.

So - I use slot 10 for my airbnb lock code.  Then I know I can use 1-9 for anything else (cleaners, my own code, etc).

**Comment by ChrisOgden** [comment]
Thank you, I will take that approach. Curious if it LCM will group the lock codes that match names and codes across devices set this way. I do have a need to have multiple codes active a times so I will need to figure out a way to round-robin a few slots.

**Comment by klinquist** [comment]
I set all my permanent lock codes through LCM
Because I have <10, it never tries to program "slot 10."

**Comment by ChrisOgden** [comment]
We have some properties with same day turnovers so there is overlap of temporary codes from time to time. I will review and make sure permanent codes are all in lower slots.
